### ISSUE TITLE
`make` fails because carto style seems to require higher mapnik version

### ISSUE THREAD

**Issue by jnachtigall** [giggls/openstreetmap-carto-de#27]
Using current master (or should I use another version?) I'm running into:

```
root@tileserver:~/software/openstreetmap-carto-de# make
carto -a 2.2.0 project.mml > /tmp/tmp.fJOldMwC3v
Error: placenames.mss:29:6 Unrecognized rule: text-margin
placenames.mss:29:6 Unrecognized rule: text-margin
placenames.mss:23:6 Unrecognized rule: text-margin
placenames.mss:17:6 Unrecognized rule: text-margin
placenames.mss:12:4 Unrecognized rule: text-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:79:4 Unrecognized rule: shield-margin
placenames.mss:79:4 Unrecognized rule: shield-margin
placenames.mss:126:6 Unrecognized rule: text-margin
placenames.mss:120:6 Unrecognized rule: text-margin
placenames.mss:112:4 Unrecognized rule: text-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:79:4 Unrecognized rule: shield-margin
placenames.mss:79:4 Unrecognized rule: shield-margin
placenames.mss:126:6 Unrecognized rule: text-margin
placenames.mss:120:6 Unrecognized rule: text-margin
placenames.mss:112:4 Unrecognized rule: text-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:79:4 Unrecognized rule: shield-margin
placenames.mss:126:6 Unrecognized rule: text-margin
placenames.mss:120:6 Unrecognized rule: text-margin
placenames.mss:112:4 Unrecognized rule: text-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:97:6 Unrecognized rule: shield-margin
placenames.mss:79:4 Unrecognized rule: shield-margin
placenames.mss:126:6 Unrecognized rule: text-margin
placenames.mss:120:6 Unrecognized rule: text-margin
placenames.mss:112:4 Unrecognized rule: text-margin
placenames.mss:62:6 Unrecognized rule: text-margin
placenames.mss:52:4 Unrecognized rule: text-margin
placenames.mss:291:8 Unrecognized rule: text-margin
placenames.mss:285:8 Unrecognized rule: text-margin
placenames.mss:279:8 Unrecognized rule: text-margin
placenames.mss:274:6 Unrecognized rule: text-margin
placenames.mss:214:6 Unrecognized rule: shield-margin
placenames.mss:214:6 Unrecognized rule: shield-margin
placenames.mss:257:8 Unrecognized rule: text-margin
placenames.mss:251:8 Unrecognized rule: text-margin
placenames.mss:245:8 Unrecognized rule: text-margin
placenames.mss:239:8 Unrecognized rule: text-margin
placenames.mss:234:6 Unrecognized rule: text-margin
placenames.mss:214:6 Unrecognized rule: shield-margin
placenames.mss:214:6 Unrecognized rule: shield-margin
placenames.mss:257:8 Unrecognized rule: text-margin
placenames.mss:251:8 Unrecognized rule: text-margin
placenames.mss:245:8 Unrecognized rule: text-margin
placenames.mss:239:8 Unrecognized rule: text-margin
placenames.mss:234:6 Unrecognized rule: text-margin
placenames.mss:214:6 Unrecognized rule: shield-margin
placenames.mss:257:8 Unrecognized rule: text-margin
placenames.mss:251:8 Unrecognized rule: text-margin
placenames.mss:245:8 Unrecognized rule: text-margin
placenames.mss:239:8 Unrecognized rule: text-margin
placenames.mss:234:6 Unrecognized rule: text-margin
placenames.mss:214:6 Unrecognized rule: shield-margin
placenames.mss:257:8 Unrecognized rule: text-margin
placenames.mss:251:8 Unrecognized rule: text-margin
placenames.mss:245:8 Unrecognized rule: text-margin
placenames.mss:239:8 Unrecognized rule: text-margin
placenames.mss:234:6 Unrecognized rule: text-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:144:6 Unrecognized rule: shield-margin
placenames.mss:144:6 Unrecognized rule: shield-margin
placenames.mss:193:8 Unrecognized rule: text-margin
placenames.mss:187:8 Unrecognized rule: text-margin
placenames.mss:179:6 Unrecognized rule: text-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:144:6 Unrecognized rule: shield-margin
placenames.mss:193:8 Unrecognized rule: text-margin
placenames.mss:187:8 Unrecognized rule: text-margin
placenames.mss:144:6 Unrecognized rule: shield-margin
placenames.mss:179:6 Unrecognized rule: text-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:144:6 Unrecognized rule: shield-margin
placenames.mss:193:8 Unrecognized rule: text-margin
placenames.mss:187:8 Unrecognized rule: text-margin
placenames.mss:179:6 Unrecognized rule: text-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:162:8 Unrecognized rule: shield-margin
placenames.mss:144:6 Unrecognized rule: shield-margin
placenames.mss:193:8 Unrecognized rule: text-margin
placenames.mss:187:8 Unrecognized rule: text-margin
placenames.mss:179:6 Unrecognized rule: text-margin
placenames.mss:394:6 Unrecognized rule: text-margin
placenames.mss:388:6 Unrecognized rule: text-margin
placenames.mss:394:6 Unrecognized rule: text-margin
placenames.mss:388:6 Unrecognized rule: text-margin
placenames.mss:394:6 Unrecognized rule: text-margin
placenames.mss:388:6 Unrecognized rule: text-margin
placenames.mss:394:6 Unrecognized rule: text-margin
placenames.mss:388:6 Unrecognized rule: text-margin
placenames.mss:394:6 Unrecognized rule: text-margin
placenames.mss:388:6 Unrecognized rule: text-margin
placenames.mss:367:8 Unrecognized rule: text-margin
placenames.mss:361:8 Unrecognized rule: text-margin
placenames.mss:355:8 Unrecognized rule: text-margin
placenames.mss:347:8 Unrecognized rule: text-margin
placenames.mss:326:6 Unrecognized rule: text-margin
placenames.mss:318:6 Unrecognized rule: text-margin
placenames.mss:312:6 Unrecognized rule: text-margin
placenames.mss:307:4 Unrecognized rule: text-margin
    at Object.env.error (/usr/local/lib/node_modules/carto/lib/carto/parser.js:241:55)
    at Rule.tree.Rule.toXML (/usr/local/lib/node_modules/carto/lib/carto/tree/rule.js:56:20)
    at Definition.tree.Definition.symbolizersToXML (/usr/local/lib/node_modules/carto/lib/carto/tree/definition.js:139:46)
    at Definition.tree.Definition.toXML (/usr/local/lib/node_modules/carto/lib/carto/tree/definition.js:203:33)
    at /usr/local/lib/node_modules/carto/lib/carto/tree/style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (/usr/local/lib/node_modules/carto/lib/carto/tree/style.js:30:29)
    at Renderer.render (/usr/local/lib/node_modules/carto/lib/carto/renderer.js:138:43)
    at compileMML (/usr/local/lib/node_modules/carto/bin/carto:87:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/carto/bin/carto:178:9)
Makefile:6: recipe for target 'osm-de.xml' failed
make: *** [osm-de.xml] Error 1
```

carto version is:
```
root@tileserver:~/software/openstreetmap-carto-de# carto -v
carto 0.16.3 (Carto map stylesheet compiler)
```

on Debian 8.7

This seems to be the same issue as mentioned at https://github.com/gravitystorm/openstreetmap-carto/pull/2470#issuecomment-266233976 which seems to caused by carto requiring the latest mapnik now (https://github.com/gravitystorm/openstreetmap-carto/pull/2470#issuecomment-266234555)

Any idea to fix this? I am not sure on how to proceed best now. 

I could manually install latest mapnik manually and try to update the Makefile. On the other hand, this might cause further dependency problems later with tirex and other debian packages.

Or is there a known openstreetmap-carto-de version that still works with mapnik 2.2? 

Or maybe really adding your deb repo from http://tile.openstreetmap.de/debian8-backports/ ?

**Comment by giggls** [comment]
As I'm closely bound to upstream you are out of luck with mapnik 2.2.

I'm using a backport of Mapnik3 myself available at http://tile.openstreetmap.de/debian8-backports/

You can add the following to /etc/apt/sources.list:
deb http://tile.openstreetmap.de/debian8-backports jessie-backports main

Regards

Sven

**Comment by jnachtigall** [comment]
Closing. Using a more recent mapnik3 fixes it. Thanks for the backports. Very much appreciated.
