### ISSUE TITLE
Does it not compile?

### ISSUE THREAD

**Issue by Quintus** [giggls/openstreetmap-carto-de#9]
Hi everyone,

forgive my ignorance, but I am unable to compile the CartoCSS stylesheet in this style (output from `master` branch at 638f325269063b99977d69be65976e8e1692c77a):

~~~~
% ../carto/bin/carto --version               
carto 0.16.3 (Carto map stylesheet compiler)
% ../carto/bin/carto project.mml > mapnik.xml 
Error: roads.mss:3104:21 variable @tertiary-shield is undefined
roads.mss:3104:21 variable @tertiary-shield is undefined
roads.mss:3104:21 variable @tertiary-shield is undefined
    at Object.env.error (/home/quintus/OSM-Karte/carto/lib/carto/parser.js:241:55)
    at Object.tree.Variable.ev (/home/quintus/OSM-Karte/carto/lib/carto/tree/variable.js:23:17)
    at Object.tree.Expression.ev (/home/quintus/OSM-Karte/carto/lib/carto/tree/expression.js:15:34)
    at Object.tree.Value.ev (/home/quintus/OSM-Karte/carto/lib/carto/tree/value.js:11:34)
    at Rule.tree.Rule.ev (/home/quintus/OSM-Karte/carto/lib/carto/tree/rule.js:115:20)
    at Definition.tree.Definition.symbolizersToXML (/home/quintus/OSM-Karte/carto/lib/carto/tree/definition.js:139:38)
    at Definition.tree.Definition.toXML (/home/quintus/OSM-Karte/carto/lib/carto/tree/definition.js:203:33)
    at /home/quintus/OSM-Karte/carto/lib/carto/tree/style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (/home/quintus/OSM-Karte/carto/lib/carto/tree/style.js:30:29)
~~~~

Maybe it's just me doing it wrong, but since documentation is rather difficult to find, I thought I'd just ask this here. If this is development-related, how do I get a stable branch to work with? The tags appear to be inherited from `openstreetmap-carto` itself?

Greetings
Marvin

**Comment by giggls** [comment]
Any reason for not using the Makefile?
Where did you get the Information from, that project.mml is the actual sourcecode of the style?
In this case it is just a verbatim copy of the upstream style and not used at all.

**Comment by hholzgra** [comment]
Was hit by a similar problem, and didn't even notice that there was a Makefile until I read about it here.

Neiter the README nor the two INSTALL files mention it?

PS: Makefile works fine, and I love the "make" approach ...
